import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Search, X, Dumbbell, Target, Zap, HeartPulse, PersonStanding, Repeat, Activity, BookOpen } from "lucide-react";

const ENHANCED_EXERCISES = [
  { id: "barbell_squat", name: "Barbell Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Hamstrings, Core", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The barbell squat is a compound lower body exercise that primarily targets the quadriceps, glutes, and hamstrings. It is considered one of the most effective exercises for building overall leg strength and muscle mass.", steps: ["Place a barbell across your upper back, resting it on your trapezius muscles", "Stand with feet shoulder-width apart, toes slightly turned out", "Brace your core and take a deep breath", "Descend by pushing your hips back and bending your knees simultaneously", "Lower until your thighs are at least parallel to the floor", "Drive through your whole foot to stand back up", "Exhale at the top and squeeze your glutes"], commonMistakes: ["Knees caving inward (valgus collapse)", "Rising onto toes during the ascent", "Rounding the lower back (butt wink)", "Not hitting adequate depth", "Leaning too far forward"], tips: ["Keep your chest up throughout the movement", "Push your knees out in the direction of your toes", "Look straight ahead or slightly upward", "Wear flat-soled shoes or go barefoot for better stability", "Start with bodyweight to master form before adding load"], gifUrl: "", defaultSets: 4, defaultReps: 8 },
  { id: "front_squat", name: "Front Squat", cat: "compound", primary: "Quadriceps", secondary: "Core, Upper Back", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The front squat places the barbell on the front of your shoulders, creating a more upright torso position. This shifts emphasis to the quadriceps and demands greater core and upper back engagement.", steps: ["Clean the barbell to the front rack position on your shoulders", "Hold the bar with a clean grip or cross-arm grip", "Stand with feet shoulder-width apart", "Keep your elbows high and chest up throughout the movement", "Descend by bending your knees and hips, keeping torso upright", "Lower to parallel or below", "Drive up through your heels, maintaining elbow height"], commonMistakes: ["Dropping the elbows and losing bar position", "Leaning forward excessively", "Not maintaining thoracic extension", "Rising onto toes"], tips: ["Practice front rack mobility drills regularly", "Focus on keeping elbows parallel to the floor", "Strengthen your upper back with rows and face pulls", "Use a wider grip if you lack wrist mobility"], gifUrl: "", defaultSets: 4, defaultReps: 6 },
  { id: "goblet_squat", name: "Goblet Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Core", equip: "Dumbbell", type: "strength", difficulty: "Beginner", description: "The goblet squat is a beginner-friendly squat variation where you hold a dumbbell or kettlebell at chest height. The counterbalance helps maintain an upright torso and teaches proper squat mechanics.", steps: ["Hold a dumbbell or kettlebell vertically at chest height with both hands", "Stand with feet slightly wider than shoulder-width", "Keep your elbows inside your knees throughout the movement", "Squat down by pushing your hips back and bending your knees", "Go as deep as comfortable while keeping your chest up", "Drive back up through your heels", "Squeeze your glutes at the top"], commonMistakes: ["Letting the weight pull you forward", "Not going deep enough", "Rising onto toes", "Knees tracking too far inward"], tips: ["Use this as a warm-up before barbell squats", "Hold the weight close to your chest", "Drive your elbows down toward your knees at the bottom", "Great for learning proper squat depth"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "leg_press", name: "Leg Press", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Hamstrings", equip: "Machine", type: "strength", difficulty: "Beginner", description: "The leg press is a machine-based compound exercise that targets the quadriceps, glutes, and hamstrings. It allows you to load the legs heavily without the balance demands of a free-weight squat.", steps: ["Sit in the leg press machine with your back flat against the pad", "Place your feet shoulder-width apart on the platform", "Release the safety catches", "Lower the platform by bending your knees toward your chest", "Stop when your knees reach approximately 90 degrees", "Press the platform back up without locking your knees", "Re-engage the safety catches when finished"], commonMistakes: ["Lowering the platform too far causing lower back rounding", "Placing feet too low on the platform", "Locking knees at the top", "Lifting hips off the pad"], tips: ["Place feet higher for more glute/hamstring emphasis", "Place feet lower for more quad emphasis", "Don't bounce at the bottom", "Keep your lower back pressed into the pad at all times"], gifUrl: "", defaultSets: 4, defaultReps: 10 },
  { id: "hack_squat", name: "Hack Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes", equip: "Machine", type: "strength", difficulty: "Beginner", description: "The hack squat machine provides a guided path for squatting, allowing you to focus on quad development with reduced spinal loading. The fixed movement pattern makes it easier to maintain proper form.", steps: ["Position yourself in the hack squat machine with shoulders under the pads", "Place feet shoulder-width apart on the platform", "Release the safety locks", "Lower the weight by bending your knees", "Descend until your thighs are parallel or slightly below", "Press back up to the starting position", "Lock the safety catches when done"], commonMistakes: ["Going too deep and losing lower back contact", "Placing feet too narrow", "Bouncing at the bottom", "Not fully extending at the top"], tips: ["Narrow stance emphasizes quads", "Wide stance targets glutes more", "Control the eccentric for better muscle growth", "Add a 2-second pause at the bottom for extra tension"], gifUrl: "", defaultSets: 4, defaultReps: 10 },
  { id: "bulgarian_split", name: "Bulgarian Split Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Hamstrings", equip: "Dumbbell", type: "strength", difficulty: "Intermediate", description: "The Bulgarian split squat is a unilateral exercise that targets each leg independently. It builds single-leg strength, improves balance, and addresses muscle imbalances between legs.", steps: ["Stand 2 feet in front of a bench, holding dumbbells at your sides", "Place the top of your rear foot on the bench behind you", "Keep your torso upright and core braced", "Lower your body by bending your front knee", "Descend until your front thigh is parallel to the floor", "Drive through your front heel to return to the starting position", "Complete all reps on one side before switching"], commonMistakes: ["Leaning too far forward", "Rear foot too close to the bench", "Knee tracking past the toes excessively", "Losing balance throughout the movement"], tips: ["Start with bodyweight to master the balance", "Place your front foot further forward for more glute emphasis", "Keep your gaze forward to maintain balance", "Use a lower bench if you have hip mobility limitations"], gifUrl: "", defaultSets: 3, defaultReps: 10 },
  { id: "walking_lunge", name: "Walking Lunge", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Hamstrings", equip: "Dumbbell", type: "strength", difficulty: "Beginner", description: "Walking lunges are a dynamic unilateral exercise that builds leg strength, stability, and coordination. The walking pattern adds a cardiovascular component and challenges balance.", steps: ["Stand tall with dumbbells at your sides", "Take a large step forward with your right leg", "Lower your body until both knees form 90-degree angles", "Push off your back foot and step it forward into the next lunge", "Alternate legs with each step", "Keep your torso upright throughout", "Continue for the desired distance or reps"], commonMistakes: ["Taking too short or too long steps", "Leaning forward excessively", "Knee collapsing inward", "Pushing off the front toes instead of the heel"], tips: ["Take longer steps to emphasize glutes", "Keep your core tight throughout", "Maintain a steady rhythm", "Start with bodyweight before adding load"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "leg_extension", name: "Leg Extension", cat: "isolation", primary: "Quadriceps", secondary: "", equip: "Machine", type: "strength", difficulty: "Beginner", description: "The leg extension is an isolation exercise that specifically targets the quadriceps muscles. It is commonly used as an accessory movement to supplement compound leg exercises.", steps: ["Sit in the leg extension machine with your back against the pad", "Adjust the roller pad to sit just above your ankles", "Grip the handles on either side", "Extend your legs by contracting your quadriceps", "Squeeze at the top for a brief moment", "Lower the weight back down with control", "Don't let the weight stack touch between reps"], commonMistakes: ["Using momentum to swing the weight", "Not squeezing at the top", "Lowering too quickly", "Using excessive weight that compromises form"], tips: ["Point your toes slightly outward for better quad contraction", "Hold the top position for 1-2 seconds", "Use this as a pre-exhaust before squats or leg presses", "Control the eccentric phase for maximum muscle growth"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "leg_curl", name: "Leg Curl", cat: "isolation", primary: "Hamstrings", secondary: "", equip: "Machine", type: "strength", difficulty: "Beginner", description: "The leg curl is an isolation exercise that specifically targets the hamstring muscles. It is important for balanced leg development and preventing hamstring injuries.", steps: ["Lie face down on the leg curl machine (or sit for seated variation)", "Position the roller pad just above your ankles", "Grip the handles for stability", "Curl your legs toward your glutes by contracting your hamstrings", "Squeeze at the top of the movement", "Lower the weight back down with control", "Don't let the weight stack touch between reps"], commonMistakes: ["Lifting your hips off the pad", "Using momentum", "Lowering too quickly", "Not getting full range of motion"], tips: ["Keep your hips pressed into the pad throughout", "Try single-leg curls to address imbalances", "Use slow eccentrics (3-4 seconds) for better hamstring development", "Pair with leg extensions for balanced leg training"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "romanian_deadlift", name: "Romanian Deadlift", cat: "compound", primary: "Hamstrings", secondary: "Glutes, Lower Back", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The Romanian deadlift is a hip-hinge exercise that primarily targets the hamstrings and glutes. It emphasizes the eccentric loading of the posterior chain and is excellent for building hamstring flexibility and strength.", steps: ["Stand with feet hip-width apart, holding a barbell with an overhand grip", "Keep a slight bend in your knees throughout", "Hinge at your hips, pushing them backward", "Lower the barbell along the front of your legs", "Go down until you feel a strong stretch in your hamstrings", "Drive your hips forward to return to standing", "Squeeze your glutes at the top"], commonMistakes: ["Rounding the lower back", "Bending the knees too much (turning it into a conventional deadlift)", "Letting the bar drift away from the body", "Not pushing hips back far enough"], tips: ["Think of pushing your hips back, not lowering the bar", "Keep the bar in contact with your legs throughout", "The range of motion is determined by your hamstring flexibility", "Use a deficit (standing on a platform) for greater range of motion"], gifUrl: "", defaultSets: 4, defaultReps: 8 },
  { id: "stiff_leg_dl", name: "Stiff-Leg Deadlift", cat: "compound", primary: "Hamstrings", secondary: "Lower Back", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The stiff-leg deadlift is similar to the Romanian deadlift but with straighter legs, which places more emphasis on the hamstrings and less on the glutes. It requires good hamstring flexibility.", steps: ["Stand with feet hip-width apart holding a barbell", "Keep your legs almost straight (slight knee bend)", "Hinge at the hips and lower the barbell", "Lower until you feel maximum hamstring stretch", "Keep your back flat throughout the movement", "Pull the barbell back up by contracting your hamstrings", "Return to the starting position"], commonMistakes: ["Rounding the lower back", "Bouncing at the bottom", "Locking the knees completely", "Using too much weight"], tips: ["Start with lighter weight to develop hamstring flexibility", "Use a wider stance for more adductor involvement", "Perform these after squats when hamstrings are warmed up", "Focus on the stretch at the bottom"], gifUrl: "", defaultSets: 3, defaultReps: 10 },
  { id: "hip_thrust", name: "Hip Thrust", cat: "compound", primary: "Glutes", secondary: "Hamstrings, Core", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The hip thrust is one of the most effective exercises for glute development. It places the glutes under maximum tension at full hip extension, making it superior to squats for targeted glute growth.", steps: ["Sit on the floor with your upper back against a bench", "Roll a barbell over your hips (use a pad for comfort)", "Plant your feet flat on the floor, shoulder-width apart", "Drive through your heels and lift your hips toward the ceiling", "Squeeze your glutes hard at the top for 1-2 seconds", "Lower your hips back down with control", "Don't let your hips drop completely to the floor between reps"], commonMistakes: ["Hyperextending the lower back at the top", "Feet too far forward or too close", "Not achieving full hip extension", "Rising onto toes"], tips: ["Tuck your chin to prevent lower back hyperextension", "Drive through your whole foot, not just your heels", "Pause at the top for maximum glute activation", "Start with bodyweight to master the hip hinge pattern"], gifUrl: "", defaultSets: 4, defaultReps: 10 },
  { id: "glute_bridge", name: "Glute Bridge", cat: "isolation", primary: "Glutes", secondary: "Hamstrings", equip: "Bodyweight", type: "strength", difficulty: "Beginner", description: "The glute bridge is a foundational bodyweight exercise for activating and strengthening the glute muscles. It is commonly used as a warm-up exercise and for rehabilitation.", steps: ["Lie on your back with knees bent and feet flat on the floor", "Place your arms at your sides with palms down", "Drive through your heels to lift your hips toward the ceiling", "Squeeze your glutes at the top for 2-3 seconds", "Lower your hips back down slowly", "Don't let your lower back arch excessively at the top", "Repeat for the desired number of reps"], commonMistakes: ["Pushing through the toes instead of heels", "Overarching the lower back", "Not squeezing the glutes at the top", "Raising hips too high"], tips: ["Focus on a 3-second squeeze at the top", "Try single-leg variations for increased difficulty", "Use this as a glute activation exercise before heavy lifting", "Place a resistance band above your knees for extra glute engagement"], gifUrl: "", defaultSets: 3, defaultReps: 15 },
  { id: "calf_raise", name: "Standing Calf Raise", cat: "isolation", primary: "Calves", secondary: "", equip: "Machine", type: "strength", difficulty: "Beginner", description: "The standing calf raise targets the gastrocnemius and soleus muscles of the calves. It is essential for developing lower leg strength and aesthetics.", steps: ["Stand on the calf raise machine with shoulders under the pads", "Place the balls of your feet on the edge of the platform", "Let your heels hang off the edge for a full stretch", "Push through the balls of your feet to raise your heels as high as possible", "Squeeze your calves at the top for 1-2 seconds", "Lower your heels back down slowly for a deep stretch", "Don't bounce at the bottom"], commonMistakes: ["Not going through full range of motion", "Bouncing at the bottom", "Using too much weight", "Not pausing at the top"], tips: ["Pause at the top for maximum contraction", "Hold the stretch at the bottom for 2 seconds", "Perform high reps (15-20) for calf growth", "Train calves 3-4 times per week for best results"], gifUrl: "", defaultSets: 4, defaultReps: 15 },
  { id: "seated_calf", name: "Seated Calf Raise", cat: "isolation", primary: "Calves", secondary: "", equip: "Machine", type: "strength", difficulty: "Beginner", description: "The seated calf raise primarily targets the soleus muscle, which lies underneath the gastrocnemius. A well-developed soleus adds width and thickness to the lower leg.", steps: ["Sit in the seated calf raise machine with knees under the pad", "Place the balls of your feet on the platform edge", "Release the safety catch", "Lower your heels for a full stretch", "Raise your heels as high as possible", "Squeeze at the top for 1-2 seconds", "Lower slowly back to the stretched position"], commonMistakes: ["Rushing through reps", "Not stretching at the bottom", "Using momentum", "Lifting with the toes instead of the balls of the feet"], tips: ["The soleus responds well to high reps (20-25)", "Slow eccentrics (3-4 seconds) are very effective", "Stretch your calves after each set", "Include both standing and seated variations for complete development"], gifUrl: "", defaultSets: 4, defaultReps: 20 },
  { id: "deadlift", name: "Conventional Deadlift", cat: "compound", primary: "Back", secondary: "Hamstrings, Glutes, Core, Forearms", equip: "Barbell", type: "strength", difficulty: "Advanced", description: "The conventional deadlift is a full-body compound exercise that targets the posterior chain including the back, glutes, hamstrings, and forearms. It is one of the three powerlifts and builds overall strength and muscle mass.", steps: ["Stand with feet hip-width apart, barbell over mid-foot", "Bend at the hips and knees to grip the bar", "Place hands slightly wider than shoulder-width with an overgrip or mixed grip", "Flatten your back, engage your lats, and brace your core", "Drive through your feet and extend your hips and knees simultaneously", "Lock out at the top with shoulders back and hips through", "Lower the bar by hinging at the hips first, then bending the knees"], commonMistakes: ["Rounding the lower back", "Starting with hips too high (stiff-legging it)", "Bar drifting away from the body", "Jerking the bar off the floor", "Hyperextending at the lockout"], tips: ["Think of pushing the floor away, not pulling the bar up", "Keep the bar in contact with your body throughout", "Engage your lats by imagining you're squeezing oranges in your armpits", "Use chalk or straps if grip is the limiting factor"], gifUrl: "", defaultSets: 4, defaultReps: 5 },
  { id: "sumo_deadlift", name: "Sumo Deadlift", cat: "compound", primary: "Back", secondary: "Quadriceps, Glutes, Hamstrings", equip: "Barbell", type: "strength", difficulty: "Advanced", description: "The sumo deadlift uses a wide stance with hands inside the knees. It emphasizes the quadriceps and inner thighs more than the conventional deadlift and can be easier on the lower back.", steps: ["Stand with feet wide apart, toes pointed outward at 30-45 degrees", "Grip the bar with hands inside your legs, shoulder-width apart", "Push your knees out in the direction of your toes", "Flatten your back and brace your core", "Drive through your feet and push the floor apart", "Lock out at the top with hips through", "Lower with control, pushing hips back"], commonMistakes: ["Knees caving inward", "Feet too wide or too narrow", "Rounding the upper back", "Leaning too far forward"], tips: ["Point your toes in the same direction as your knees", "Keep your chest tall throughout", "Focus on pushing your knees out to engage your glutes", "Great for lifters with longer torsos or shorter arms"], gifUrl: "", defaultSets: 4, defaultReps: 5 },
  { id: "barbell_row", name: "Barbell Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts, Core", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The barbell row is a fundamental back exercise that builds thickness and strength in the upper back. It targets the lats, rhomboids, rear delts, and biceps while challenging core stability.", steps: ["Stand with feet hip-width apart, holding a barbell with an overhand grip", "Hinge at the hips until your torso is approximately 45 degrees", "Keep your back flat and core braced", "Pull the barbell toward your lower ribcage", "Squeeze your shoulder blades together at the top", "Lower the bar with control", "Maintain the same torso angle throughout"], commonMistakes: ["Standing too upright (turning it into a shrug)", "Using momentum to swing the weight", "Rounding the upper back", "Pulling to the wrong area"], tips: ["Pull the bar toward your belly button for more lat engagement", "Pull toward your chest for more upper back emphasis", "Think about pulling with your elbows, not your hands", "Use a controlled tempo: 1 second up, 2 seconds down"], gifUrl: "", defaultSets: 4, defaultReps: 8 },
  { id: "pendlay_row", name: "Pendlay Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The Pendlay row is a strict barbell row variation where each rep starts from the floor. It builds explosive pulling power and reinforces proper rowing mechanics.", steps: ["Stand with feet hip-width apart, barbell on the floor", "Hinge at the hips until your torso is parallel to the floor", "Grip the bar slightly wider than shoulder-width", "Pull the bar explosively to your lower chest/upper abdomen", "The bar must return to a dead stop on the floor each rep", "Maintain a flat back throughout", "Don't let your torso rise during the pull"], commonMistakes: ["Using body English to cheat the rep", "Not returning the bar to the floor", "Rounding the back", "Torso rising during the pull"], tips: ["Each rep should be explosive from a dead stop", "Keep your torso strictly parallel to the floor", "Use a controlled negative if you want more hypertrophy", "This is a power exercise, not a hypertrophy exercise by nature"], gifUrl: "", defaultSets: 4, defaultReps: 6 },
  { id: "dumbbell_row", name: "Dumbbell Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts", equip: "Dumbbell", type: "strength", difficulty: "Beginner", description: "The single-arm dumbbell row is a unilateral back exercise that allows you to focus on each side independently. It helps address muscle imbalances and provides a great stretch at the bottom.", steps: ["Place your left knee and left hand on a flat bench", "Hold a dumbbell in your right hand with arm extended", "Keep your back flat and parallel to the bench", "Pull the dumbbell toward your hip, leading with your elbow", "Squeeze your lat at the top of the movement", "Lower the dumbbell with control until your arm is fully extended", "Complete all reps on one side before switching"], commonMistakes: ["Rotating the torso to cheat the weight up", "Not going through full range of motion", "Rounding the back", "Shrugging the shoulder up"], tips: ["Think about pulling the dumbbell to your back pocket", "Get a full stretch at the bottom by letting your shoulder drop", "Keep your core tight to prevent torso rotation", "Use a neutral grip for better lat engagement"], gifUrl: "", defaultSets: 3, defaultReps: 10 },
  { id: "cable_row", name: "Cable Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts", equip: "Cable", type: "strength", difficulty: "Beginner", description: "The cable row provides constant tension throughout the range of motion, making it excellent for building back thickness. The cable setup allows for various grip positions to target different back muscles.", steps: ["Sit at the cable row station with feet on the footplates", "Grab the handle with your chosen grip", "Sit upright with a slight bend in your knees", "Pull the handle toward your midsection", "Squeeze your shoulder blades together at the peak contraction", "Slowly extend your arms back to the starting position", "Let your shoulders protract slightly for a full stretch"], commonMistakes: ["Leaning too far back", "Using momentum to initiate the pull", "Not achieving full contraction", "Rounding the lower back"], tips: ["Try different grips: close, wide, V-bar, rope", "Lean slightly forward at the start for a greater stretch", "Think about pulling your elbows behind your body", "Hold the contraction for 1-2 seconds"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "lat_pulldown", name: "Lat Pulldown", cat: "compound", primary: "Back", secondary: "Biceps", equip: "Cable", type: "strength", difficulty: "Beginner", description: "The lat pulldown is a machine-based exercise that targets the latissimus dorsi. It is an excellent exercise for building back width and is a regression of the pull-up.", steps: ["Sit at the lat pulldown machine with thighs secured under the pads", "Grip the wide bar with an overhand grip, wider than shoulder-width", "Lean back slightly and puff your chest out", "Pull the bar down toward your upper chest", "Squeeze your lats at the bottom of the movement", "Slowly return the bar to the starting position", "Don't let the weight stack touch between reps"], commonMistakes: ["Leaning too far back (turning it into a row)", "Pulling behind the neck", "Using momentum to swing the weight", "Not achieving full stretch at the top"], tips: ["Pull to your upper chest, not behind your neck", "Think about driving your elbows down and back", "Use a close grip or V-bar for more inner back emphasis", "Control the negative for 2-3 seconds"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "pull_up", name: "Pull-Up", cat: "compound", primary: "Back", secondary: "Biceps, Core", equip: "Bodyweight", type: "strength", difficulty: "Intermediate", description: "The pull-up is a fundamental bodyweight exercise that builds back width and upper body strength. It primarily targets the lats while engaging the biceps, core, and forearms.", steps: ["Grip a pull-up bar with an overhand grip, hands slightly wider than shoulder-width", "Hang with arms fully extended (dead hang)", "Engage your lats by depressing your shoulder blades", "Pull yourself up by driving your elbows down", "Continue until your chin is above the bar", "Lower yourself back down with control", "Return to a full dead hang before the next rep"], commonMistakes: ["Using kipping or momentum", "Not going through full range of motion", "Shrugging the shoulders", "Crossing the legs behind (minor, but upright is better for form awareness)"], tips: ["Start with negatives (jumping up, lowering slowly) if you can't do a full pull-up", "Use resistance bands for assistance", "Focus on the eccentric for building strength", "Aim for full range of motion on every rep"], gifUrl: "", defaultSets: 4, defaultReps: 8 },
  { id: "chin_up", name: "Chin-Up", cat: "compound", primary: "Back", secondary: "Biceps, Core", equip: "Bodyweight", type: "strength", difficulty: "Intermediate", description: "The chin-up uses an underhand (supinated) grip, which engages the biceps more than a standard pull-up. It is generally easier than a pull-up due to greater bicep contribution.", steps: ["Grip a pull-up bar with an underhand grip, hands shoulder-width apart", "Hang with arms fully extended", "Pull yourself up by flexing your elbows and engaging your lats", "Continue until your chin clears the bar", "Lower yourself back down with control", "Don't swing or kip", "Complete all reps before releasing the bar"], commonMistakes: ["Using momentum or kipping", "Not going to full extension", "Leaning too far back", "Crossing legs and creating momentum"], tips: ["The chin-up is a great stepping stone to the pull-up", "Focus on keeping your core tight to prevent swinging", "Try a neutral grip (palms facing each other) as a middle ground", "Great exercise for building bicep mass alongside back width"], gifUrl: "", defaultSets: 4, defaultReps: 8 },
  { id: "face_pull", name: "Face Pull", cat: "isolation", primary: "Rear Delts", secondary: "Rotator Cuff", equip: "Cable", type: "strength", difficulty: "Beginner", description: "The face pull is a crucial exercise for shoulder health and posture. It strengthens the rear delts, rotator cuff, and upper back muscles that are often weakened by overhead pressing and desk work.", steps: ["Set a cable pulley to face height with a rope attachment", "Grip both ends of the rope with palms facing each other", "Step back until there is tension on the cable", "Pull the rope toward your face, separating your hands", "Externally rotate your shoulders at the end position", "Squeeze your rear delts for 1-2 seconds", "Slowly return to the starting position"], commonMistakes: ["Using too much weight", "Not externally rotating at the end", "Pulling too low (below face level)", "Rounding the shoulders forward"], tips: ["Use this exercise at least 3 times per week for shoulder health", "Keep your elbows at or above shoulder height", "Think about pulling the rope apart, not just pulling back", "Use light weight with high reps (15-20)"], gifUrl: "", defaultSets: 3, defaultReps: 15 },
  { id: "bench_press", name: "Barbell Bench Press", cat: "compound", primary: "Chest", secondary: "Triceps, Front Delts", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The barbell bench press is the most popular chest exercise and one of the three powerlifts. It builds chest mass, tricep strength, and anterior deltoid development.", steps: ["Lie on a flat bench with your eyes under the bar", "Grip the bar slightly wider than shoulder-width", "Unrack the bar and hold it over your chest with arms locked", "Lower the bar to your mid-chest with control", "Press the bar back up to the starting position", "Keep your shoulder blades retracted and feet flat on the floor", "Don't bounce the bar off your chest"], commonMistakes: ["Flaring the elbows out too wide", "Lifting hips off the bench", "Bouncing the bar off the chest", "Uneven lockout (one arm finishing before the other)"], tips: ["Tuck your elbows at about 45 degrees to protect your shoulders", "Drive your feet into the floor for leg drive", "Retract and depress your shoulder blades into the bench", "Use a spotter for heavy sets"], gifUrl: "", defaultSets: 4, defaultReps: 8 },
  { id: "incline_bench", name: "Incline Bench Press", cat: "compound", primary: "Chest", secondary: "Front Delts, Triceps", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The incline bench press targets the upper portion of the pectoralis major. It also places greater emphasis on the front deltoids compared to the flat bench press.", steps: ["Set the bench to a 30-45 degree incline", "Grip the bar slightly wider than shoulder-width", "Unrack the bar and hold it over your upper chest", "Lower the bar to your upper chest/collarbone area", "Press the bar back up to the starting position", "Keep your shoulder blades pressed into the bench", "Don't let the bar drift too far forward"], commonMistakes: ["Setting the incline too high (becomes a shoulder press)", "Gripping too wide", "Lowering to the wrong spot on the chest", "Arching excessively"], tips: ["30 degrees is optimal for upper chest emphasis", "Higher than 45 degrees shifts focus to shoulders", "Control the eccentric for better upper chest development", "Pair with flat bench for complete chest training"], gifUrl: "", defaultSets: 4, defaultReps: 8 },
  { id: "db_bench_press", name: "Dumbbell Bench Press", cat: "compound", primary: "Chest", secondary: "Triceps, Front Delts", equip: "Dumbbell", type: "strength", difficulty: "Intermediate", description: "The dumbbell bench press allows for a greater range of motion than the barbell version and helps address strength imbalances between sides. It also requires more stabilization, engaging more muscle fibers.", steps: ["Lie on a flat bench holding a dumbbell in each hand", "Start with the dumbbells at chest level, palms facing forward", "Press both dumbbells up simultaneously", "Bring the dumbbells together at the top", "Lower them back to the starting position with control", "Keep your feet flat on the floor", "Don't let the dumbbells drift outward"], commonMistakes: ["Letting the dumbbells drift too wide", "Not getting a full stretch at the bottom", "Using momentum to get the dumbbells up", "Uneven pressing (one arm leading the other)"], tips: ["Get a partner to help lift heavy dumbbells into position", "Squeeze the dumbbells together at the top for extra chest activation", "Control the eccentric for maximum muscle growth", "Rotate your palms slightly inward at the top for a better squeeze"], gifUrl: "", defaultSets: 3, defaultReps: 10 },
  { id: "cable_fly", name: "Cable Fly", cat: "isolation", primary: "Chest", secondary: "Front Delts", equip: "Cable", type: "strength", difficulty: "Beginner", description: "The cable fly provides constant tension throughout the range of motion, making it excellent for chest isolation. The cables allow you to adjust the angle to target different areas of the chest.", steps: ["Set both cable pulleys to an appropriate height", "Grab a handle in each hand and step forward", "Stand with a slight forward lean and one foot in front of the other", "With a slight bend in your elbows, bring your hands together in front of your chest", "Squeeze your chest at the peak contraction", "Slowly return your arms to the starting position", "Feel the stretch across your chest at the bottom"], commonMistakes: ["Using too much weight", "Bending the elbows too much (turning it into a press)", "Using momentum", "Not achieving full stretch or contraction"], tips: ["High-to-low cables target the lower chest", "Low-to-high cables target the upper chest", "Keep a slight bend in your elbows throughout", "Focus on the squeeze at the center, not the weight"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "push_up", name: "Push-Up", cat: "compound", primary: "Chest", secondary: "Triceps, Core, Front Delts", equip: "Bodyweight", type: "strength", difficulty: "Beginner", description: "The push-up is a fundamental bodyweight exercise that builds chest, tricep, and core strength. It can be performed anywhere and has numerous variations for all fitness levels.", steps: ["Start in a plank position with hands slightly wider than shoulder-width", "Keep your body in a straight line from head to heels", "Lower your chest toward the floor by bending your elbows", "Go until your chest is just above the floor", "Push back up to the starting position", "Keep your core tight throughout", "Don't let your hips sag or pike up"], commonMistakes: ["Letting the hips sag (anterior pelvic tilt)", "Piking the hips up", "Not going through full range of motion", "Flaring elbows out too wide"], tips: ["Think about pushing the floor away from you", "Keep your elbows at about 45 degrees", "Squeeze your glutes and brace your core throughout", "Elevate your feet for more difficulty or use a bench"], gifUrl: "", defaultSets: 3, defaultReps: 15 },
  { id: "ohp", name: "Overhead Press", cat: "compound", primary: "Shoulders", secondary: "Triceps, Core", equip: "Barbell", type: "strength", difficulty: "Intermediate", description: "The overhead press is a fundamental pressing movement that builds shoulder strength and size. It is one of the four powerlifting movements and develops the deltoids, triceps, and core.", steps: ["Stand with feet shoulder-width apart, gripping the bar at shoulder width", "Hold the bar at collarbone height with elbows slightly in front", "Brace your core and squeeze your glutes", "Press the bar straight up over your head", "Move your head slightly back to clear the bar path", "Lock out the bar directly over your midfoot", "Lower the bar back to the starting position with control"], commonMistakes: ["Excessive back lean (turning it into an incline press)", "Pressing the bar forward instead of straight up", "Not bracing the core", "Flaring elbows out too wide"], tips: ["Squeeze your glutes to prevent excessive back lean", "Think about pushing your head through the window at the top", "Start with a strict press, add push press for heavier loads", "Keep the bar path as vertical as possible"], gifUrl: "", defaultSets: 4, defaultReps: 6 },
  { id: "db_ohp", name: "Dumbbell Shoulder Press", cat: "compound", primary: "Shoulders", secondary: "Triceps", equip: "Dumbbell", type: "strength", difficulty: "Intermediate", description: "The dumbbell shoulder press allows each arm to work independently, helping address imbalances and allowing for a greater range of motion than the barbell version.", steps: ["Sit on a bench with back support, holding dumbbells at shoulder height", "Position the dumbbells with palms facing forward", "Press both dumbbells overhead simultaneously", "Bring the dumbbells close together at the top without clanging", "Lower them back to shoulder height with control", "Keep your back against the pad throughout", "Don't arch your lower back excessively"], commonMistakes: ["Arching the lower back", "Pressing the dumbbells too far forward", "Not going through full range of motion", "Using momentum"], tips: ["Sitting version prevents using leg drive for strict isolation", "Try the Arnold press variation for greater range of motion", "Keep your core braced throughout", "Control the negative for 2-3 seconds"], gifUrl: "", defaultSets: 3, defaultReps: 10 },
  { id: "lateral_raise", name: "Lateral Raise", cat: "isolation", primary: "Side Delts", secondary: "", equip: "Dumbbell", type: "strength", difficulty: "Beginner", description: "The lateral raise is the primary exercise for developing the medial (side) deltoid, which creates the wide shoulder appearance. It is an isolation movement that should be performed with controlled form.", steps: ["Stand with feet shoulder-width apart, dumbbells at your sides", "With a slight bend in your elbows, raise the dumbbells out to the sides", "Lift until your arms are parallel to the floor", "Lead with your elbows, not your hands", "Hold the top position for 1-2 seconds", "Lower the dumbbells slowly back to the starting position", "Don't use momentum to swing the weight up"], commonMistakes: ["Using too much weight", "Swinging the dumbbells up", "Raising the arms too high (above parallel)", "Rolling the shoulders forward"], tips: ["Use lighter weight with perfect form", "Pour water from a jug motion at the top", "Think about pouring water out of two jugs", "Try cable lateral raises for constant tension"], gifUrl: "", defaultSets: 4, defaultReps: 15 },
  { id: "rear_delt_fly", name: "Rear Delt Fly", cat: "isolation", primary: "Rear Delts", secondary: "", equip: "Dumbbell", type: "strength", difficulty: "Beginner", description: "The rear delt fly targets the posterior deltoid, which is often neglected in training. Strong rear delts improve posture, shoulder health, and create a balanced, three-dimensional shoulder appearance.", steps: ["Sit on the edge of a bench, leaning forward with dumbbells hanging below", "With a slight bend in your elbows, raise the dumbbells out to the sides", "Squeeze your rear delts at the top of the movement", "Lower the dumbbells back down with control", "Keep your torso relatively stationary throughout", "Don't use momentum to swing the weight", "Perform each rep deliberately"], commonMistakes: ["Using too much weight", "Raising the dumbbells too high", "Using momentum", "Engaging the traps instead of rear delts"], tips: ["Use very light weight for this exercise", "Think about squeezing a pencil between your shoulder blades", "Try the bent-over cable reverse fly for constant tension", "Perform these at the start of a workout for pre-activation"], gifUrl: "", defaultSets: 3, defaultReps: 15 },
  { id: "barbell_curl", name: "Barbell Curl", cat: "isolation", primary: "Biceps", secondary: "Forearms", equip: "Barbell", type: "strength", difficulty: "Beginner", description: "The barbell curl is the classic bicep building exercise. It allows you to load the biceps heavily and build overall bicep mass and strength.", steps: ["Stand with feet shoulder-width apart, holding a barbell with an underhand grip", "Keep your elbows close to your body throughout", "Curl the barbell up by flexing your elbows", "Squeeze your biceps at the top of the movement", "Lower the barbell back down with control", "Don't swing your body to cheat the weight up", "Keep your upper arms stationary throughout"], commonMistakes: ["Swinging the body to generate momentum", "Letting the elbows drift forward", "Not going through full range of motion", "Lowering too quickly"], tips: ["Keep your elbows pinned to your sides", "Use an EZ-bar for more comfortable wrist position", "Control the negative for 2-3 seconds", "Try the 21s technique: 7 bottom half, 7 top half, 7 full range"], gifUrl: "", defaultSets: 3, defaultReps: 10 },
  { id: "hammer_curl", name: "Hammer Curl", cat: "isolation", primary: "Biceps", secondary: "Forearms, Brachialis", equip: "Dumbbell", type: "strength", difficulty: "Beginner", description: "The hammer curl targets the brachialis and brachioradialis in addition to the biceps. It builds arm thickness and improves grip strength.", steps: ["Stand with dumbbells at your sides, palms facing each other", "Keep your elbows close to your body", "Curl both dumbbells up simultaneously", "Keep your palms facing each other throughout", "Squeeze at the top for 1-2 seconds", "Lower the dumbbells back down with control", "Don't swing or use momentum"], commonMistakes: ["Rotating the wrist during the curl", "Using momentum", "Letting the elbows drift forward", "Going too heavy"], tips: ["Keep a neutral grip (palms facing each other) throughout", "Try cross-body hammer curls for more brachialis emphasis", "Great exercise for building forearm and grip strength", "Alternate arms for a more controlled movement"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "tricep_pushdown", name: "Tricep Pushdown", cat: "isolation", primary: "Triceps", secondary: "", equip: "Cable", type: "strength", difficulty: "Beginner", description: "The tricep pushdown is the most common tricep isolation exercise. It provides constant tension through the cable and can be performed with various attachments to target all three tricep heads.", steps: ["Stand at a cable machine with a high pulley and straight bar or rope", "Grip the attachment with palms facing down", "Keep your elbows pinned to your sides", "Push the attachment down by extending your elbows", "Lock out your arms at the bottom and squeeze your triceps", "Slowly return to the starting position", "Don't let your elbows drift forward"], commonMistakes: ["Leaning too far forward", "Letting elbows drift away from the body", "Using momentum", "Not fully extending at the bottom"], tips: ["Use a rope for better lateral head activation", "Spread the rope apart at the bottom for extra contraction", "Keep your upper arms completely stationary", "Try overhead extensions for the long head emphasis"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "skull_crusher", name: "Skull Crusher", cat: "isolation", primary: "Triceps", secondary: "", equip: "EZ-Bar", type: "strength", difficulty: "Intermediate", description: "The skull crusher (lying tricep extension) is a highly effective tricep isolation exercise. It targets all three heads of the triceps, especially the long head.", steps: ["Lie on a flat bench holding an EZ-bar with an overhand grip", "Extend your arms straight above your chest", "Keeping your upper arms stationary, bend your elbows", "Lower the bar toward your forehead (or slightly behind)", "Extend your elbows to return to the starting position", "Keep your elbows pointed toward the ceiling throughout", "Don't flare your elbows outward"], commonMistakes: ["Flaring elbows outward", "Moving the upper arms", "Lowering the bar too close to the face", "Using too much weight"], tips: ["Point your elbows slightly toward your head for better long head stretch", "Try lowering behind your head for a greater stretch", "Use an EZ-bar for more comfortable wrist positioning", "Keep a controlled tempo throughout"], gifUrl: "", defaultSets: 3, defaultReps: 10 },
  { id: "plank", name: "Plank", cat: "isolation", primary: "Core", secondary: "Shoulders, Glutes", equip: "Bodyweight", type: "strength", difficulty: "Beginner", description: "The plank is a fundamental isometric core exercise that builds stability and endurance in the abdominal muscles, lower back, and shoulders. It strengthens the entire core without spinal flexion.", steps: ["Start in a forearm plank position with elbows under shoulders", "Extend your legs behind you, resting on your toes", "Keep your body in a perfectly straight line from head to heels", "Engage your core by bracing as if someone were about to punch you", "Keep your hips level — don't let them sag or pike up", "Hold the position for the desired duration", "Breathe steadily throughout"], commonMistakes: ["Hips sagging toward the floor", "Hips piking up too high", "Holding your breath", "Resting on the wrong part of the forearms"], tips: ["Start with 20-30 seconds and build up to 60+", "Keep your glutes squeezed for better core engagement", "Don't look up — keep a neutral neck position", "Try side planks for oblique development"], gifUrl: "", defaultSets: 3, defaultReps: 60 },
  { id: "hanging_leg_raise", name: "Hanging Leg Raise", cat: "isolation", primary: "Core", secondary: "Hip Flexors", equip: "Bodyweight", type: "strength", difficulty: "Intermediate", description: "The hanging leg raise is one of the most effective exercises for targeting the lower abdominals and hip flexors. Hanging from a bar also provides a spinal decompression benefit.", steps: ["Hang from a pull-up bar with an overhand grip", "Keep your legs straight and together", "Raise your legs by flexing at the hips", "Continue until your legs are parallel to the floor (or higher)", "Curl your pelvis slightly at the top for full abdominal engagement", "Lower your legs slowly back to the starting position", "Don't swing or use momentum"], commonMistakes: ["Using momentum to swing the legs up", "Not going through full range of motion", "Rounding the back excessively", "Shrugging the shoulders"], tips: ["Start with bent knee raises if straight leg is too difficult", "Control the negative for 2-3 seconds", "Don't swing — if you start swinging, stop and reset", "Try to raise your legs higher than parallel for maximum contraction"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "russian_twist", name: "Russian Twist", cat: "isolation", primary: "Core", secondary: "Obliques", equip: "Bodyweight", type: "strength", difficulty: "Beginner", description: "The Russian twist targets the obliques and rotational core strength. It involves rotating the torso from side to side while maintaining a V-sit position.", steps: ["Sit on the floor with knees bent and feet elevated slightly", "Lean back at about a 45-degree angle", "Hold your hands together in front of your chest", "Rotate your torso to the right, touching the floor beside your hip", "Rotate to the left side in the same manner", "Continue alternating sides", "Keep your core engaged throughout"], commonMistakes: ["Moving the arms instead of the torso", "Not rotating enough", "Leaning too far back or forward", "Letting the feet touch the ground"], tips: ["Hold a medicine ball or weight plate for added resistance", "Keep your eyes following your hands for full rotation", "Focus on quality rotation rather than speed", "Keep your chest proud and back straight"], gifUrl: "", defaultSets: 3, defaultReps: 20 },
  { id: "dead_bug", name: "Dead Bug", cat: "isolation", primary: "Core", secondary: "", equip: "Bodyweight", type: "strength", difficulty: "Beginner", description: "The dead bug is a low-impact core exercise that builds deep core stability and coordination. It teaches you to maintain a neutral spine while moving your limbs, which translates to better performance in compound lifts.", steps: ["Lie on your back with arms extended toward the ceiling", "Lift your legs with knees bent at 90 degrees", "Press your lower back firmly into the floor", "Simultaneously extend your right arm overhead and left leg straight out", "Return to the starting position", "Repeat on the opposite side", "Keep your lower back pressed into the floor throughout"], commonMistakes: ["Lifting the lower back off the floor", "Moving too fast", "Not fully extending the limbs", "Holding your breath"], tips: ["Exhale as you extend, inhale as you return", "Move slowly and deliberately for maximum core activation", "Keep your lower back glued to the floor at all times", "Great exercise for rehab and prehab"], gifUrl: "", defaultSets: 3, defaultReps: 12 },
  { id: "kettlebell_swing", name: "Kettlebell Swing", cat: "compound", primary: "Glutes", secondary: "Hamstrings, Core, Shoulders", equip: "Kettlebell", type: "strength", difficulty: "Intermediate", description: "The kettlebell swing is a dynamic hip-hinge exercise that builds explosive power in the posterior chain. It trains the glutes, hamstrings, core, and shoulders while providing a cardiovascular challenge.", steps: ["Stand with feet slightly wider than shoulder-width", "Hold the kettlebell with both hands in front of you", "Hinge at the hips, pushing them backward", "Swing the kettlebell between your legs", "Explosively drive your hips forward", "Swing the kettlebell to chest height", "Let the kettlebell swing back down and repeat"], commonMistakes: ["Squatting instead of hinging", "Using the arms to lift the kettlebell", "Hyperextending the lower back at the top", "Not hinging deep enough"], tips: ["The power comes from the hips, not the arms", "Think about snapping your hips forward explosively", "Keep your core tight throughout the movement", "Start with a lighter weight to master the hip hinge pattern"], gifUrl: "", defaultSets: 3, defaultReps: 15 },
  { id: "burpee", name: "Burpee", cat: "bodyweight", primary: "Full Body", secondary: "Chest, Core, Legs", equip: "Bodyweight", type: "cardio", difficulty: "Intermediate", description: "The burpee is a full-body exercise that combines a squat, plank, push-up, and jump into one dynamic movement. It builds cardiovascular endurance, muscular endurance, and full-body coordination.", steps: ["Stand with feet shoulder-width apart", "Drop into a squat position and place your hands on the floor", "Jump your feet back into a plank position", "Perform a push-up (optional for advanced)", "Jump your feet back to the squat position", "Explosively jump up with arms overhead", "Land softly and immediately go into the next rep"], commonMistakes: ["Not going through the full range of motion", "Sagging the hips during the plank phase", "Landing stiffly on the jump", "Resting between reps instead of maintaining pace"], tips: ["Scale the movement: step back instead of jumping for lower intensity", "Focus on smooth, continuous movement rather than speed", "Breathe rhythmically — exhale on the jump", "Use burpees as a finisher or conditioning tool"], gifUrl: "", defaultSets: 3, defaultReps: 10 },
  { id: "mountain_climber", name: "Mountain Climber", cat: "bodyweight", primary: "Core", secondary: "Shoulders, Hip Flexors", equip: "Bodyweight", type: "cardio", difficulty: "Beginner", description: "Mountain climbers are a dynamic core and cardiovascular exercise. They engage the abs, hip flexors, shoulders, and legs while elevating heart rate for a metabolic conditioning effect.", steps: ["Start in a push-up/plank position", "Keep your body in a straight line", "Drive your right knee toward your chest", "Quickly switch and drive your left knee toward your chest", "Continue alternating at a rapid pace", "Keep your hips level and core engaged", "Breathe rhythmically throughout"], commonMistakes: ["Letting the hips pike up", "Not bringing knees far enough forward", "Going too fast and losing form", "Looking up instead of keeping neutral neck"], tips: ["Start slow and gradually increase speed", "Keep your weight over your hands", "Focus on driving knees to the chest, not just alternating feet", "Great for warm-ups, conditioning, or between strength sets"], gifUrl: "", defaultSets: 3, defaultReps: 20 },
  { id: "box_jump", name: "Box Jump", cat: "plyometric", primary: "Quadriceps", secondary: "Glutes, Calves", equip: "Bodyweight", type: "power", difficulty: "Intermediate", description: "The box jump is a plyometric exercise that develops explosive leg power, speed, and coordination. It trains the fast-twitch muscle fibers in the legs for athletic performance.", steps: ["Stand facing a sturdy box or platform", "Feet shoulder-width apart, arms at your sides", "Swing your arms back and load your hips", "Explosively jump up and onto the box", "Land softly with both feet on the box", "Stand up fully on the box", "Step down carefully (don't jump down)"], commonMistakes: ["Jumping down from the box (high injury risk)", "Landing with stiff knees", "Using a box that's too high", "Not fully extending at the top"], tips: ["Start with a lower box and work up", "Always step down, don't jump down", "Land softly — it should be nearly silent", "Focus on explosive takeoff, not just landing"], gifUrl: "", defaultSets: 4, defaultReps: 6 },
  { id: "power_clean", name: "Power Clean", cat: "compound", primary: "Full Body", secondary: "Back, Shoulders, Legs", equip: "Barbell", type: "olympic", difficulty: "Advanced", description: "The power clean is an Olympic lift variation that develops explosive full-body power. It trains the posterior chain, core, and upper body in a single explosive pulling movement.", steps: ["Start with the barbell on the floor, feet hip-width apart", "Grip the bar slightly wider than shoulder-width", "Lift the bar by extending hips and knees simultaneously", "As the bar passes your knees, explosively extend your hips", "Shrug your shoulders and pull yourself under the bar", "Catch the bar in a front rack position", "Stand up fully to complete the lift"], commonMistakes: ["Pulling with the arms too early", "Not extending the hips fully", "Catching with stiff legs", "Letting the bar drift away from the body"], tips: ["Master the hang power clean before doing it from the floor", "Focus on triple extension (ankles, knees, hips)", "Keep the bar close to your body throughout", "Practice with a PVC pipe to learn the movement pattern"], gifUrl: "", defaultSets: 5, defaultReps: 3 },
  { id: "farmers_walk", name: "Farmer's Walk", cat: "compound", primary: "Forearms", secondary: "Traps, Core, Shoulders", equip: "Dumbbell", type: "strength", difficulty: "Beginner", description: "The farmer's walk is a simple but highly effective exercise for building grip strength, core stability, and overall work capacity. It trains multiple muscle groups simultaneously.", steps: ["Pick up a heavy dumbbell or kettlebell in each hand", "Stand tall with your chest up and shoulders back", "Walk forward with controlled, steady steps", "Keep your core braced throughout", "Don't let the weights swing or your body lean", "Walk for the desired distance or time", "Set the weights down with control"], commonMistakes: ["Letting the shoulders round forward", "Walking too fast and losing control", "Gripping too loosely", "Leaning to one side with uneven weights"], tips: ["Use the heaviest weight you can maintain with good posture", "Keep your eyes forward, not at the ground", "Short, quick steps are more efficient than long strides", "Great finisher at the end of a workout"], gifUrl: "", defaultSets: 3, defaultReps: 40 },
];

const MUSCLE_GROUPS = [...new Set(ENHANCED_EXERCISES.map(e => e.primary))].sort();
const EQUIPMENT_TYPES = [...new Set(ENHANCED_EXERCISES.map(e => e.equip))].sort();
const DIFFICULTY_LEVELS = ["Beginner", "Intermediate", "Advanced"];

const CAT_ICONS = {
  compound: Dumbbell,
  isolation: Target,
  plyometric: Zap,
  cardio: HeartPulse,
  bodyweight: PersonStanding,
};

const catTitle = c => c.charAt(0).toUpperCase() + c.slice(1);
const diffClass = d => d === "Beginner" ? "green" : d === "Advanced" ? "red" : "orange";

const CatIcon = ({ cat, size = 20 }) => {
  const Icon = CAT_ICONS[cat] || Dumbbell;
  return <Icon size={size} />;
};

export default function ExerciseLibrary({ state, dispatch }) {
  const [search, setSearch] = useState("");
  const [muscleFilter, setMuscleFilter] = useState("");
  const [equipFilter, setEquipFilter] = useState("");
  const [diffFilter, setDiffFilter] = useState("");
  const [selectedExercise, setSelectedExercise] = useState(null);

  const filtered = useMemo(() => {
    return ENHANCED_EXERCISES.filter(e => {
      if (search && !e.name.toLowerCase().includes(search.toLowerCase())) return false;
      if (muscleFilter && e.primary !== muscleFilter) return false;
      if (equipFilter && e.equip !== equipFilter) return false;
      if (diffFilter && e.difficulty !== diffFilter) return false;
      return true;
    });
  }, [search, muscleFilter, equipFilter, diffFilter]);

  const hasFilters = search || muscleFilter || equipFilter || diffFilter;

  const clearFilters = () => {
    setSearch("");
    setMuscleFilter("");
    setEquipFilter("");
    setDiffFilter("");
  };

  const chip = (key, active, onClick, children) => (
    <button key={key} className={`rd-chip ${active ? "active" : ""}`} onClick={onClick}>{children}</button>
  );

  const sectionTitle = (text, color) => (
    <div style={{ fontSize: 13, fontWeight: 800, color: color || "#C8FF32", margin: "18px 0 10px" }}>{text}</div>
  );

  return (
    <div className="rd-page">
      <div className="rd-page-head">
        <div>
          <span className="rd-kicker"><BookOpen size={13} /> Library</span>
          <h1 className="rd-title">Exercise Library</h1>
          <p className="rd-sub">Browse exercises with detailed instructions, tips, and muscle targeting.</p>
        </div>
      </div>

      <div className="rd-search">
        <Search size={16} />
        <input placeholder="Search exercises..." value={search} onChange={e => setSearch(e.target.value)} />
      </div>

      <div className="rd-card rd-filter-card" style={{ padding: "16px 18px" }}>
        <div className="rd-filter-row">
          <span className="rd-filter-label">Muscle</span>
          {chip("m-all", !muscleFilter, () => setMuscleFilter(""), "All Muscles")}
          {MUSCLE_GROUPS.map(m => chip(`m-${m}`, muscleFilter === m, () => setMuscleFilter(muscleFilter === m ? "" : m), m))}
        </div>
        <div className="rd-filter-row">
          <span className="rd-filter-label">Equipment</span>
          {chip("e-all", !equipFilter, () => setEquipFilter(""), "All Equipment")}
          {EQUIPMENT_TYPES.map(e => chip(`e-${e}`, equipFilter === e, () => setEquipFilter(equipFilter === e ? "" : e), e))}
        </div>
        <div className="rd-filter-row">
          <span className="rd-filter-label">Difficulty</span>
          {chip("d-all", !diffFilter, () => setDiffFilter(""), "All Levels")}
          {DIFFICULTY_LEVELS.map(d => chip(`d-${d}`, diffFilter === d, () => setDiffFilter(diffFilter === d ? "" : d), d))}
        </div>
      </div>

      <div className="rd-count"><b>{filtered.length}</b> exercise{filtered.length !== 1 ? "s" : ""} found</div>

      {filtered.length === 0 ? (
        <div className="rd-card rd-empty" style={{ padding: "48px 16px" }}>
          <div className="rd-empty-title">No exercises found</div>
          <div className="rd-empty-sub">Try adjusting your search or clearing the active filters.</div>
          {hasFilters && <button className="rd-btn-secondary" onClick={clearFilters} style={{ marginTop: 8, padding: "10px 18px" }}>Clear Filters</button>}
        </div>
      ) : (
        <div className="rd-ex-grid">
          {filtered.map(ex => {
            return (
              <motion.div key={ex.id} className="rd-ex-card" initial={{ opacity: 0 }} animate={{ opacity: 1 }} onClick={() => setSelectedExercise(ex)}>
                <div className="rd-ex-top">
                  <div className="rd-ex-tile"><CatIcon cat={ex.cat} /></div>
                  <div className="rd-ex-body">
                    <div className="rd-ex-name">{ex.name}</div>
                    <div className="rd-ex-sub">{ex.primary}{ex.secondary ? ` · ${ex.secondary.split(",")[0]}` : ""}</div>
                  </div>
                </div>
                <div className="rd-ex-tags">
                  <span className="rd-ex-tag">{ex.primary}</span>
                  <span className={`rd-ex-tag ${diffClass(ex.difficulty)}`}>{ex.difficulty}</span>
                  <span className="rd-ex-tag muted">{ex.equip}</span>
                </div>
                <div className="rd-ex-meta">
                  <span className="rd-ex-meta-item"><Repeat size={14} /> <b>{ex.defaultSets} × {ex.defaultReps}</b></span>
                  <span className="rd-ex-meta-item"><Activity size={14} /> {ex.type}</span>
                </div>
              </motion.div>
            );
          })}
        </div>
      )}
      
      <AnimatePresence>
        {selectedExercise && (
          <motion.div className="rd-modal-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelectedExercise(null)}>
            <motion.div className="rd-modal rd-modal-lg" initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.96 }} onClick={e => e.stopPropagation()}>
              <button className="rd-modal-close" onClick={() => setSelectedExercise(null)}><X size={15} /></button>

              <div className="rd-ex-top" style={{ marginBottom: 14 }}>
                <div className="rd-ex-tile" style={{ width: 52, height: 52, borderRadius: 15 }}>
                  <CatIcon cat={selectedExercise.cat} size={24} />
                </div>
                <div className="rd-ex-body">
                  <div className="rd-modal-title">{selectedExercise.name}</div>
                  <div className="rd-ex-sub">{selectedExercise.primary}{selectedExercise.secondary ? ` · ${selectedExercise.secondary}` : ""}</div>
                </div>
              </div>

              <div className="rd-ex-tags">
                <span className="rd-ex-tag">{selectedExercise.primary}</span>
                {selectedExercise.secondary && <span className="rd-ex-tag muted">{selectedExercise.secondary}</span>}
                <span className="rd-ex-tag blue">{catTitle(selectedExercise.cat)}</span>
                <span className={`rd-ex-tag ${diffClass(selectedExercise.difficulty)}`}>{selectedExercise.difficulty}</span>
                <span className="rd-ex-tag muted">{selectedExercise.equip}</span>
              </div>

              <div style={{ height: 160, borderRadius: 14, background: "#171717", border: "1px solid rgba(255,255,255,0.06)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 10, marginTop: 16, overflow: "hidden" }}>
                {selectedExercise.gifUrl ? (
                  <img src={selectedExercise.gifUrl} alt={selectedExercise.name} style={{ width: "100%", height: "100%", objectFit: "contain" }} />
                ) : (
                  <>
                    <Zap size={28} style={{ color: "rgba(200,255,50,0.4)" }} />
                    <span style={{ fontSize: 12, color: "rgba(255,255,255,0.35)" }}>Animation / GIF coming soon</span>
                  </>
                )}
              </div>

              <p style={{ fontSize: 13, lineHeight: 1.7, color: "rgba(255,255,255,0.75)", marginTop: 16 }}>{selectedExercise.description}</p>

              {sectionTitle("Steps")}
              {selectedExercise.steps.map((step, i) => (
                <div key={i} style={{ display: "flex", gap: 10, marginBottom: 8, fontSize: 13, lineHeight: 1.6, color: "#E8E8E8" }}>
                  <span style={{ minWidth: 22, height: 22, borderRadius: 6, background: "rgba(200,255,50,0.1)", color: "#C8FF32", fontSize: 11, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{i + 1}</span>
                  <span>{step}</span>
                </div>
              ))}

              {sectionTitle("Common Mistakes", "#FF5A5F")}
              {selectedExercise.commonMistakes.map((m, i) => (
                <div key={i} style={{ fontSize: 13, color: "#FF5A5F", marginBottom: 4, paddingLeft: 16, position: "relative" }}>
                  <span style={{ position: "absolute", left: 0 }}>•</span>{m}
                </div>
              ))}

              {sectionTitle("Tips", "#4ADE80")}
              {selectedExercise.tips.map((t, i) => (
                <div key={i} style={{ fontSize: 13, color: "#4ADE80", marginBottom: 4, paddingLeft: 16, position: "relative" }}>
                  <span style={{ position: "absolute", left: 0 }}>•</span>{t}
                </div>
              ))}

              <button
                className="rd-btn-primary"
                style={{ width: "100%", marginTop: 22 }}
                onClick={() => {
                  dispatch({ type: "ADD_EXERCISE_TO_SESSION", payload: { id: selectedExercise.id, name: selectedExercise.name, cat: selectedExercise.cat, primary: selectedExercise.primary, secondary: selectedExercise.secondary, equip: selectedExercise.equip, type: selectedExercise.type, sets: Array.from({ length: selectedExercise.defaultSets }, (_, i) => ({ set: i + 1, weight: 0, reps: selectedExercise.defaultReps, rpe: "", done: false })), notes: "" } });
                  setSelectedExercise(null);
                  window.__setPage && window.__setPage("workout");
                }}
              >
                <Dumbbell size={16} /> Add to Workout
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
export { ENHANCED_EXERCISES };
