export const fmt = (n, dec = 0) => Number(n).toFixed(dec);
export const today = () => new Date().toISOString().split("T")[0];
export const weekAgo = () => { const d = new Date(); d.setDate(d.getDate() - 7); return d.toISOString().split("T")[0]; };
export const uid = () => Math.random().toString(36).slice(2, 11) + Date.now().toString(36);

export const EXERCISE_DB = [
  { id: "barbell_squat", name: "Barbell Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Hamstrings, Core", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "front_squat", name: "Front Squat", cat: "compound", primary: "Quadriceps", secondary: "Core, Upper Back", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 6 },
  { id: "goblet_squat", name: "Goblet Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Core", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "leg_press", name: "Leg Press", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Hamstrings", equip: "Machine", type: "strength", defaultSets: 4, defaultReps: 10 },
  { id: "hack_squat", name: "Hack Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes", equip: "Machine", type: "strength", defaultSets: 4, defaultReps: 10 },
  { id: "bulgarian_split", name: "Bulgarian Split Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Hamstrings", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "walking_lunge", name: "Walking Lunge", cat: "compound", primary: "Quadriceps", secondary: "Glutes, Hamstrings", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "leg_extension", name: "Leg Extension", cat: "isolation", primary: "Quadriceps", secondary: "", equip: "Machine", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "leg_curl", name: "Leg Curl", cat: "isolation", primary: "Hamstrings", secondary: "", equip: "Machine", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "romanian_deadlift", name: "Romanian Deadlift", cat: "compound", primary: "Hamstrings", secondary: "Glutes, Lower Back", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "stiff_leg_dl", name: "Stiff-Leg Deadlift", cat: "compound", primary: "Hamstrings", secondary: "Lower Back", equip: "Barbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "hip_thrust", name: "Hip Thrust", cat: "compound", primary: "Glutes", secondary: "Hamstrings, Core", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 10 },
  { id: "glute_bridge", name: "Glute Bridge", cat: "isolation", primary: "Glutes", secondary: "Hamstrings", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 15 },
  { id: "calf_raise", name: "Standing Calf Raise", cat: "isolation", primary: "Calves", secondary: "", equip: "Machine", type: "strength", defaultSets: 4, defaultReps: 15 },
  { id: "seated_calf", name: "Seated Calf Raise", cat: "isolation", primary: "Calves", secondary: "", equip: "Machine", type: "strength", defaultSets: 4, defaultReps: 20 },
  { id: "deadlift", name: "Conventional Deadlift", cat: "compound", primary: "Back", secondary: "Hamstrings, Glutes, Core, Forearms", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 5 },
  { id: "sumo_deadlift", name: "Sumo Deadlift", cat: "compound", primary: "Back", secondary: "Quadriceps, Glutes, Hamstrings", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 5 },
  { id: "barbell_row", name: "Barbell Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts, Core", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "pendlay_row", name: "Pendlay Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 6 },
  { id: "dumbbell_row", name: "Dumbbell Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "cable_row", name: "Cable Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts", equip: "Cable", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "lat_pulldown", name: "Lat Pulldown", cat: "compound", primary: "Back", secondary: "Biceps", equip: "Cable", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "pull_up", name: "Pull-Up", cat: "compound", primary: "Back", secondary: "Biceps, Core", equip: "Bodyweight", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "chin_up", name: "Chin-Up", cat: "compound", primary: "Back", secondary: "Biceps, Core", equip: "Bodyweight", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "seated_row_machine", name: "Seated Row Machine", cat: "compound", primary: "Back", secondary: "Biceps", equip: "Machine", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "tbar_row", name: "T-Bar Row", cat: "compound", primary: "Back", secondary: "Biceps, Rear Delts", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "face_pull", name: "Face Pull", cat: "isolation", primary: "Rear Delts", secondary: "Rotator Cuff", equip: "Cable", type: "strength", defaultSets: 3, defaultReps: 15 },
  { id: "shrug", name: "Barbell Shrug", cat: "isolation", primary: "Traps", secondary: "Forearms", equip: "Barbell", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "bench_press", name: "Barbell Bench Press", cat: "compound", primary: "Chest", secondary: "Triceps, Front Delts", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "incline_bench", name: "Incline Bench Press", cat: "compound", primary: "Chest", secondary: "Front Delts, Triceps", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "decline_bench", name: "Decline Bench Press", cat: "compound", primary: "Chest", secondary: "Triceps", equip: "Barbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "db_bench_press", name: "Dumbbell Bench Press", cat: "compound", primary: "Chest", secondary: "Triceps, Front Delts", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "db_incline_press", name: "Incline Dumbbell Press", cat: "compound", primary: "Chest", secondary: "Front Delts, Triceps", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "cable_fly", name: "Cable Fly", cat: "isolation", primary: "Chest", secondary: "Front Delts", equip: "Cable", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "db_fly", name: "Dumbbell Fly", cat: "isolation", primary: "Chest", secondary: "Front Delts", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "chest_dip", name: "Chest Dip", cat: "compound", primary: "Chest", secondary: "Triceps, Front Delts", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "push_up", name: "Push-Up", cat: "compound", primary: "Chest", secondary: "Triceps, Core, Front Delts", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 15 },
  { id: "machine_chest_press", name: "Machine Chest Press", cat: "compound", primary: "Chest", secondary: "Triceps, Front Delts", equip: "Machine", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "ohp", name: "Overhead Press", cat: "compound", primary: "Shoulders", secondary: "Triceps, Core", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 6 },
  { id: "db_ohp", name: "Dumbbell Shoulder Press", cat: "compound", primary: "Shoulders", secondary: "Triceps", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "arnold_press", name: "Arnold Press", cat: "compound", primary: "Shoulders", secondary: "Triceps", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "lateral_raise", name: "Lateral Raise", cat: "isolation", primary: "Side Delts", secondary: "", equip: "Dumbbell", type: "strength", defaultSets: 4, defaultReps: 15 },
  { id: "front_raise", name: "Front Raise", cat: "isolation", primary: "Front Delts", secondary: "", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "rear_delt_fly", name: "Rear Delt Fly", cat: "isolation", primary: "Rear Delts", secondary: "", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 15 },
  { id: "cable_lateral", name: "Cable Lateral Raise", cat: "isolation", primary: "Side Delts", secondary: "", equip: "Cable", type: "strength", defaultSets: 3, defaultReps: 15 },
  { id: "machine_shoulder", name: "Machine Shoulder Press", cat: "compound", primary: "Shoulders", secondary: "Triceps", equip: "Machine", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "upright_row", name: "Upright Row", cat: "compound", primary: "Shoulders", secondary: "Traps, Biceps", equip: "Barbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "barbell_curl", name: "Barbell Curl", cat: "isolation", primary: "Biceps", secondary: "Forearms", equip: "Barbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "db_curl", name: "Dumbbell Curl", cat: "isolation", primary: "Biceps", secondary: "Forearms", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "hammer_curl", name: "Hammer Curl", cat: "isolation", primary: "Biceps", secondary: "Forearms, Brachialis", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "preacher_curl", name: "Preacher Curl", cat: "isolation", primary: "Biceps", secondary: "", equip: "EZ-Bar", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "cable_curl", name: "Cable Curl", cat: "isolation", primary: "Biceps", secondary: "", equip: "Cable", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "concentration_curl", name: "Concentration Curl", cat: "isolation", primary: "Biceps", secondary: "", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "tricep_pushdown", name: "Tricep Pushdown", cat: "isolation", primary: "Triceps", secondary: "", equip: "Cable", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "skull_crusher", name: "Skull Crusher", cat: "isolation", primary: "Triceps", secondary: "", equip: "EZ-Bar", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "overhead_ext", name: "Overhead Tricep Extension", cat: "isolation", primary: "Triceps", secondary: "", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "dip_tricep", name: "Tricep Dip", cat: "compound", primary: "Triceps", secondary: "Chest, Front Delts", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "close_grip_bench", name: "Close-Grip Bench Press", cat: "compound", primary: "Triceps", secondary: "Chest, Front Delts", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 6 },
  { id: "french_press", name: "French Press", cat: "isolation", primary: "Triceps", secondary: "", equip: "EZ-Bar", type: "strength", defaultSets: 3, defaultReps: 10 },
  { id: "wrist_curl", name: "Wrist Curl", cat: "isolation", primary: "Forearms", secondary: "", equip: "Barbell", type: "strength", defaultSets: 3, defaultReps: 15 },
  { id: "reverse_curl", name: "Reverse Curl", cat: "isolation", primary: "Forearms", secondary: "Biceps", equip: "EZ-Bar", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "plank", name: "Plank", cat: "isolation", primary: "Core", secondary: "Shoulders, Glutes", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 60 },
  { id: "crunch", name: "Crunch", cat: "isolation", primary: "Core", secondary: "", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 20 },
  { id: "hanging_leg_raise", name: "Hanging Leg Raise", cat: "isolation", primary: "Core", secondary: "Hip Flexors", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "russian_twist", name: "Russian Twist", cat: "isolation", primary: "Core", secondary: "Obliques", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 20 },
  { id: "ab_rollout", name: "Ab Rollout", cat: "compound", primary: "Core", secondary: "Lats, Shoulders", equip: "Ab Wheel", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "cable_crunch", name: "Cable Crunch", cat: "isolation", primary: "Core", secondary: "", equip: "Cable", type: "strength", defaultSets: 3, defaultReps: 15 },
  { id: "dead_bug", name: "Dead Bug", cat: "isolation", primary: "Core", secondary: "", equip: "Bodyweight", type: "strength", defaultSets: 3, defaultReps: 12 },
  { id: "turkish_getup", name: "Turkish Get-Up", cat: "compound", primary: "Core", secondary: "Shoulders, Hips, Full Body", equip: "Kettlebell", type: "strength", defaultSets: 3, defaultReps: 5 },
  { id: "kettlebell_swing", name: "Kettlebell Swing", cat: "compound", primary: "Glutes", secondary: "Hamstrings, Core, Shoulders", equip: "Kettlebell", type: "strength", defaultSets: 3, defaultReps: 15 },
  { id: "clean_and_jerk", name: "Clean and Jerk", cat: "compound", primary: "Full Body", secondary: "Back, Shoulders, Legs", equip: "Barbell", type: "olympic", defaultSets: 5, defaultReps: 3 },
  { id: "snatch", name: "Snatch", cat: "compound", primary: "Full Body", secondary: "Back, Shoulders, Legs", equip: "Barbell", type: "olympic", defaultSets: 5, defaultReps: 3 },
  { id: "power_clean", name: "Power Clean", cat: "compound", primary: "Full Body", secondary: "Back, Shoulders, Legs", equip: "Barbell", type: "olympic", defaultSets: 5, defaultReps: 3 },
  { id: "push_press", name: "Push Press", cat: "compound", primary: "Shoulders", secondary: "Triceps, Legs", equip: "Barbell", type: "strength", defaultSets: 4, defaultReps: 5 },
  { id: "box_jump", name: "Box Jump", cat: "plyometric", primary: "Quadriceps", secondary: "Glutes, Calves", equip: "Bodyweight", type: "power", defaultSets: 4, defaultReps: 6 },
  { id: "burpee", name: "Burpee", cat: "bodyweight", primary: "Full Body", secondary: "Chest, Core, Legs", equip: "Bodyweight", type: "cardio", defaultSets: 3, defaultReps: 10 },
  { id: "mountain_climber", name: "Mountain Climber", cat: "bodyweight", primary: "Core", secondary: "Shoulders, Hip Flexors", equip: "Bodyweight", type: "cardio", defaultSets: 3, defaultReps: 20 },
  { id: "jump_squat", name: "Jump Squat", cat: "plyometric", primary: "Quadriceps", secondary: "Glutes, Calves", equip: "Bodyweight", type: "power", defaultSets: 3, defaultReps: 12 },
  { id: "battle_ropes", name: "Battle Ropes", cat: "cardio", primary: "Shoulders", secondary: "Core, Arms", equip: "Bands", type: "cardio", defaultSets: 3, defaultReps: 30 },
  { id: "farmers_walk", name: "Farmer's Walk", cat: "compound", primary: "Forearms", secondary: "Traps, Core, Shoulders", equip: "Dumbbell", type: "strength", defaultSets: 3, defaultReps: 40 },
  { id: "sled_push", name: "Sled Push", cat: "cardio", primary: "Quadriceps", secondary: "Glutes, Calves, Core", equip: "Machine", type: "cardio", defaultSets: 4, defaultReps: 30 },
  { id: "rowing_machine", name: "Rowing Machine", cat: "cardio", primary: "Back", secondary: "Legs, Core, Biceps", equip: "Machine", type: "cardio", defaultSets: 1, defaultReps: 500 },
  { id: "bike", name: "Stationary Bike", cat: "cardio", primary: "Quadriceps", secondary: "Hamstrings, Calves", equip: "Machine", type: "cardio", defaultSets: 1, defaultReps: 1 },
  { id: "treadmill", name: "Treadmill Running", cat: "cardio", primary: "Quadriceps", secondary: "Calves, Glutes, Core", equip: "Machine", type: "cardio", defaultSets: 1, defaultReps: 1 },
  { id: "assault_bike", name: "Assault Bike", cat: "cardio", primary: "Full Body", secondary: "Legs, Arms, Core", equip: "Machine", type: "cardio", defaultSets: 1, defaultReps: 1 },
  { id: "smith_machine_squat", name: "Smith Machine Squat", cat: "compound", primary: "Quadriceps", secondary: "Glutes", equip: "Smith Machine", type: "strength", defaultSets: 4, defaultReps: 8 },
  { id: "smith_machine_bench", name: "Smith Machine Bench Press", cat: "compound", primary: "Chest", secondary: "Triceps, Front Delts", equip: "Smith Machine", type: "strength", defaultSets: 4, defaultReps: 8 },
];
export const EXERCISES = EXERCISE_DB.map(e => e.name);
export const MUSCLE_GROUPS = [...new Set(EXERCISE_DB.map(e => e.primary))].sort();
export const EQUIPMENT_TYPES = [...new Set(EXERCISE_DB.map(e => e.equip))].sort();
export const EXERCISE_CATEGORIES = [...new Set(EXERCISE_DB.map(e => e.cat))].sort();

export const GOAL_LABELS = { muscle: "Build Muscle", fat_loss: "Fat Loss", strength: "Strength", endurance: "Endurance", powerlifting: "Powerlifting", bodybuilding: "Bodybuilding", general: "General Fitness" };
export const BADGE_DEFS = [
  { id: "first_workout", label: "First Workout", desc: "Logged your first session" },
  { id: "week_streak", label: "7-Day Streak", desc: "7 consecutive active days" },
  { id: "ten_workouts", label: "10 Workouts", desc: "Completed 10 workouts" },
  { id: "hundred_workouts", label: "100 Workouts", desc: "Century club" },
  { id: "volume_1000", label: "1000kg Volume", desc: "1000kg in a single session" },
  { id: "nutrition_week", label: "Nutrition Week", desc: "7 days of nutrition tracking" },
];
export const COLORS = { primary: "#22C55E", cyan: "#22C55E", green: "#22C55E", amber: "#F59E0B", red: "#EF4444", blue: "#3B82F6", gold: "#FFD700", surface: "rgba(255,255,255,0.04)", border: "rgba(255,255,255,0.08)" };
export const SAVE_ACTIONS = new Set([
  "ADD_WORKOUT", "FINISH_SESSION",
  "ADD_NUTRITION", "EDIT_NUTRITION", "DELETE_NUTRITION", "DUPLICATE_NUTRITION",
  "ADD_RECOVERY", "ADD_WEIGHT", "LOG_WATER", "SET_WATER",
  "SAVE_RUN", "DELETE_RUN", "SET_RUNNING_GOALS",
  "ADD_GOAL", "UPDATE_GOAL", "DELETE_GOAL",
  "SAVE_PROGRAM", "UPDATE_PROGRAM", "DELETE_PROGRAM", "SET_ACTIVE_PROGRAM",
  "SAVE_TEMPLATE", "DELETE_TEMPLATE", "UPDATE_TEMPLATE",
  "ADD_CUSTOM_EXERCISE", "DELETE_CUSTOM_EXERCISE",
  "ADD_FAVORITE_MEAL", "REMOVE_FAVORITE_MEAL",
  "UPDATE_PROFILE", "COMPLETE_ONBOARDING", "SAVE_BODY_RESULTS",
  "UPDATE_SETTINGS", "RESET",
  "ADD_NOTIFICATION", "CLEAR_NOTIFICATIONS",
  "MARK_NOTIFICATION_READ",
]);
export const GUEST_PROFILE = {
  name: "Guest", email: "", photoURL: "", goal: "general", activity: "moderate",
  tdee: 2200, calories: 2000, protein: 150, age: 25, weight: 70, height: 175,
};
export const ACTIVITY_MULTIPLIERS = { sedentary: 1.2, light: 1.375, moderate: 1.55, active: 1.725, very_active: 1.9 };

export const PAGES = [
  { id: "dashboard", label: "Dashboard", group: "main" },
  { id: "workout", label: "Workouts", group: "training" },
  { id: "exercise-library", label: "Exercise Library", group: "training" },
  { id: "planner", label: "Workout Planner", group: "training" },
  { id: "running", label: "Running", group: "training" },
  { id: "programs", label: "Programs", group: "training" },
  { id: "nutrition", label: "Nutrition", group: "health" },
  { id: "smart-nutrition", label: "Smart Nutrition", group: "health" },
  { id: "water-tracker", label: "Water Tracker", group: "health" },
  { id: "calculator", label: "BMI Calculator", group: "health" },
  { id: "recovery", label: "Recovery", group: "health" },
  { id: "bodyweight", label: "Body Weight", group: "health" },
  { id: "goals", label: "Goals", group: "analytics" },
  { id: "achievements", label: "Achievements", group: "analytics" },
  { id: "progress", label: "Progress", group: "analytics" },
  { id: "coach", label: "AI Coach", group: "analytics" },
  { id: "notifications", label: "Notifications", group: "tools" },
  { id: "export", label: "Export Reports", group: "tools" },
  { id: "admin", label: "Analytics", group: "tools" },
  { id: "settings", label: "Settings", group: "account" },
  { id: "profile", label: "Profile", group: "account" },
];

export const SIDEBAR_GROUPS = [
  { key: "main", label: "" },
  { key: "training", label: "TRAINING" },
  { key: "health", label: "HEALTH" },
  { key: "analytics", label: "ANALYTICS" },
  { key: "tools", label: "TOOLS" },
  { key: "account", label: "ACCOUNT" },
];

export const MOCK_DELAY = () => 600 + Math.random() * 900;
export const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

export const MOCK_COACHING = {
  workout_review: [
    "Solid session! Your volume is trending upward which is great for hypertrophy. Keep pushing progressive overload — even 1-2.5kg more per week compounds fast.",
    "Good consistency this week. I'd suggest adding 1 working set to your compound lifts for extra volume. Recovery looks adequate so you can handle it.",
    "Nice work! Your estimated 1RM is climbing. Make sure you're hitting at least 1.6g protein/kg bodyweight to support this training load.",
    "Training frequency looks good. Consider adding a rest-pause set on your last working set to increase intensity without extra fatigue.",
    "Great session. Your RPE scores suggest you have 1-2 reps in reserve on most sets — perfect for long-term progress without burnout.",
    "Volume is in a good range. If progress stalls, try a deload week at 60% intensity before pushing again. Recovery is where gains are made.",
  ],
  workout_tip: [
    "Focus on eccentric control — a 3-second lowering phase increases time under tension and muscle damage for better growth.",
    "Try supersetting antagonist muscle groups (e.g., chest/back) to save time and increase training density.",
    "Warm up with 2-3 ramping sets before your working weight. This primes your nervous system and reduces injury risk.",
    "For your next session, try cluster sets: 5x2 with 20s rest between reps. Great for building strength at heavier loads.",
    "Consider adding 5 minutes of loaded carries at the end of your workout. It builds grip, core stability, and work capacity.",
    "Your last set should be close to failure (RPE 9-10). Leave nothing in the tank on that final push.",
  ],
  nutrition: [
    "You're close to your protein target! Try adding a casein shake before bed — it digestslowly and supports overnight muscle protein synthesis.",
    "For your remaining calories today, focus on whole foods: chicken breast, rice, and vegetables. Micronutrients matter as much as macros.",
    "Great protein intake today. Consider timing 30-40g of protein within 2 hours post-workout for optimal recovery.",
    "Your carbs are a bit low. Add some oats or sweet potato around your training window to fuel performance and recovery.",
    "Hydration check: aim for at least 3L of water today, especially on training days. Dehydration can reduce strength by 10-15%.",
    "Try meal prepping on Sundays. Having food ready removes decision fatigue and makes hitting your targets much easier.",
  ],
  recovery: [
    "Your recovery score looks good! 7+ hours of quality sleep is the single most important recovery tool. Keep it consistent.",
    "Stress is elevated today. Consider 10 minutes of light walking or stretching. Active recovery beats complete rest for reducing cortisol.",
    "Your sleep quality is below average. Try limiting screen time 1 hour before bed and keeping your room cool (18-20C).",
    "Recovery is solid. You're ready for a high-intensity session today. Push for new PRs on your main lifts.",
    "With your current recovery score, I'd recommend a moderate session — focus on technique and volume over intensity.",
    "Low recovery detected. Today is a perfect day for mobility work, foam rolling, or a light swim. Don't force a heavy session.",
  ],
  general: [
    "Consistency beats perfection. Missing one workout isn't the end — just get back on track the next day. The long game is what matters.",
    "Progressive overload is the key driver of all adaptation. Track your lifts and always aim to do slightly more than last time.",
    "Your training age matters. As a beginner, focus on mastering form. Intermediate? Chase progressive overload. Advanced? Manage fatigue.",
    "Remember: muscles grow during recovery, not in the gym. Prioritize sleep, nutrition, and stress management alongside training.",
    "A good program followed consistently beats a perfect program done sporadically. Stick with your plan for at least 8-12 weeks.",
    "Don't neglect mobility work. 10 minutes of stretching post-workout can prevent injuries and improve range of motion over time.",
  ],
};
